# Generated by Django 4.0.1 on 2022-01-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_dashboardm_event_participant_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='R_type',
            field=models.TextField(max_length=70),
        ),
    ]
