# Generated by Django 4.0.1 on 2022-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=70)),
                ('Description', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=70)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('R_d_date', models.DateField()),
                ('H_email', models.EmailField(max_length=100)),
                ('H_password', models.CharField(max_length=100)),
            ],
        ),
    ]
