# Generated by Django 4.0.1 on 2022-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboardm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.CharField(max_length=50)),
                ('H_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=70)),
                ('Description', models.CharField(max_length=70)),
                ('Location', models.CharField(max_length=70)),
                ('s_date', models.DateTimeField()),
                ('e_date', models.DateTimeField()),
                ('R_d_date', models.DateTimeField()),
                ('H_email', models.EmailField(max_length=254)),
                ('H_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('c_no', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('Event', models.BooleanField()),
                ('R_type', models.BooleanField()),
                ('N_people', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
