# Generated by Django 4.0.1 on 2022-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_participant_event_alter_participant_r_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='R_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=30),
        ),
    ]
